
--returns a string
function MediaPlayer.PackDefaultPresets()
	local tab = {}
	local str = "MediaPlayerPresets = {"

	if (!file.IsDir("data/presets/", "thirdparty")) then
		warning("data/presets/ not found in addon directory")
		return
	end

	local files = file.Find("data/presets/*.json", "thirdparty")

	for k,v in pairs(files) do

		v = string.Replace(v, " ", "_")
		tab[ v ] = file.Read("data/presets/" .. v , "thirdparty")
	end

	for k,v in pairs(tab) do
		str = str .. "\n" .. string.format("['%s'] = [[%s]],\n", k, v )
	end

	str = str .. "}"

	return str
end

function MediaPlayer.PrintDefaultPresets()

	local str = MediaPlayer.PackDefaultPresets()

	print("--COPY BELOW THIS LINE into lua/autorun/prsets.lua--\n")
	str = "--autogenerated " .. util.DateStamp() .. "\n\n" .. str
	print(str)
	print("\n--COPY ABOVE THIS LINE into lua/autorun/prsets.lua--")
end

function MediaPlayer.GetPackedPresets()

	--this global is loaded from autorun
	if ( MediaPlayerPresets == nil or table.IsEmpty(MediaPlayerPresets )) then
		return
	end

	return MediaPlayerPresets;
end

function MediaPlayer.CreateWarningBox(title, message, timeout)
	timeout = timeout or false

	MediaPlayer.ReinstantiatePanel("WarningBox")
	MediaPlayer.GetPanel("WarningBox"):SetWarning(title, message, timeout)
end


function MediaPlayer.CreateSuccessBox(title, message, timeout)
	timeout = timeout or false

	MediaPlayer.ReinstantiatePanel("SuccessBox")
	MediaPlayer.GetPanel("SuccessBox"):SetBox(title, message, timeout)
end


function MediaPlayer.RequestDefaultPreset()

	net.Start("MediaPlayer.RequestDefaultPreset")
	net.SendToServer()
end

function MediaPlayer.RefreshDefaultPreset()

	net.Start("MediaPlayer.RequestRefreshDefaultPreset")
		--nope
	net.SendToServer()
end

function MediaPlayer.RequestDefaultInitialPreset()

	net.Start("MediaPlayer.RequestDefaultInitialPreset")
	net.SendToServer()
end

function MediaPlayer.ApplyInitialPreset(preset)

	if (!MediaPlayer.LocalPlayer:IsAdmin()) then return end

	if (table.IsEmpty(preset) or preset.Settings == nil ) then
		error("bad preset")
	end

	for k,v in pairs(preset.Settings) do

		if (type(v) == "table") then

			local set = MediaPlayer.GetSetting(k).DefValue
			for key,val in pairs(v) do

				if (set.__pack != nil and string.sub(key, 1, 2) != "__" ) then
					v[key] = set.__pack(v[key], key, val )
				end

				if (string.sub(key, 1, 2) == "__") then
					v[key] = nil
					continue
				end
			end
		end
	end

	print("sending initial preset to server")
	net.Start("MediaPlayer.ApplyInitialPreset")
		net.WriteTable(preset)
	net.SendToServer()
end